/**
 * Generated by @openapi-codegen
 *
 * @version v1
 */
import * as reactQuery from "react-query";
import { useNsContext, NsContext } from "./nsContext";
import type * as Fetcher from "./nsFetcher";
import { nsFetch } from "./nsFetcher";

export type QueryOperation = {
  path: string;
  operationId: never;
  variables: unknown;
};
